### ISSUE TITLE
Make the segment option `g` accept text

### ISSUE THREAD

**Issue by k3rni** [tpwres/teczki-polskiego-wrestlingu#975]
The two examples below should be equivalent in all aspects:

Currently:

```yaml
- - Stone Cold Steve Austin
  - g: true
    s: The famous 3:16 promo
```

Preferred:

```yaml
- - Stone Cold Steve Austin
  - g: The famous 3:16 promo
```
